import "./styles/globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

export const metadata = {
  title: "Portfolio Website",
  description: "Generated by Khuzaima Nazik",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-bodyFont">
        <Header/>
        <StairTransition/>
        <PageTransition> {children}</PageTransition>
       </body>
    </html>
  );
}
